# Generated by Django 5.1.6 on 2025-02-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academic_year', models.CharField(max_length=50)),
            ],
        ),
    ]
