# Generated by Django 5.1.6 on 2025-02-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_rename_department_id_tbl_staff_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=50)),
                ('hod_email', models.EmailField(max_length=50)),
                ('hod_contact', models.CharField(max_length=50)),
                ('hod_photo', models.FileField(upload_to='hod/')),
                ('hod_password', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department')),
            ],
        ),
    ]
