# Generated by Django 5.1.6 on 2025-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_hod',
            name='hod_photo',
            field=models.FileField(upload_to='Assets/Hod/'),
        ),
    ]
