# Generated by Django 5.1.7 on 2025-03-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_timeslot_tbl_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_timeslot',
            name='end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_timeslot',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
    ]
