# Generated by Django 5.1.6 on 2025-02-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_teachersubject',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='tbl_teachersubject',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
